//************************************************************************************
//**  
//**  Source name:   D:\Campus\sem 6\CO326  Computer Systems Engineering Industrial Networks\labs\test1\Flowcode1.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.18F.18F4550
//**  
//**  Generated by:  Flowcode v7.1.1.0
//**  Date:          Tuesday, January 15, 2019 14:06:44
//**  Users:         1
//**  Registered to: 
//**  Licence key:   *****
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixtsl.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 19660800

#define FCP_NULL Unconnected_Port



#include <xc.h>
#include <math.h>

__PROG_CONFIG(0x1, 0xFEEC);
__PROG_CONFIG(0x2, 0xFEFF);
__PROG_CONFIG(0x3, 0xFFFF);
__PROG_CONFIG(0x4, 0xFF9B);
__PROG_CONFIG(0x5, 0xFFFF);
__PROG_CONFIG(0x6, 0xFFFF);
__PROG_CONFIG(0x7, 0xFFFF);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\Program Files (x86)\Flowcode 7\CAL\internals.c"



/*========================================================================*\
   Use :panel
       :Variable declarations
       :Macro function declarations
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_UINT8 FCV_DATA;
MX_GLOBAL MX_UINT8 FCV_INPUT_SWITCHES;


/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\Program Files (x86)\Flowcode 7\CAL\includes.c"


/*========================================================================*\
   Use :panel
       :Macro implementations
\*========================================================================*/


/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
ADCON0=0x00;
ADCON1 = 0x0F;
UCFG = 0x08;
cr_bit(PIE2, USBIE);




	// Output
	// Output: 0xff -> PORTD
	FCP_SET(F, D, 0xFF, 0, (0xff));
	// Output
	// Output: 1 -> A1
	FCP_SET(B, A, 0x02, 1, (1));
	// Delay
	// Delay: 100 ms
	FCI_DELAYBYTE_MS(100);

	// Output
	// Output: 1 -> A0
	FCP_SET(B, A, 0x01, 0, (1));
	// Output
	// Output: 0 -> PORTD
	FCP_SET(F, D, 0xFF, 0, (0));
	// Delay
	// Delay: 1000 ms
	FCI_DELAYINT_MS(1000);

	// Loop
	// Loop: While 1
	while (1)
	{

		// Input
		// Input: PORTB -> input_switches
		FCV_INPUT_SWITCHES = FCP_GET(F, B, 0xFF, 0);
		// Delay
		// Delay: 10 ms
		FCI_DELAYBYTE_MS(10);

		// Output
		// Output: input_switches -> PORTD
		FCP_SET(F, D, 0xFF, 0, (FCV_INPUT_SWITCHES));

	}

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{

}




