//************************************************************************************
//**  
//**  Source name:   C:\Users\Gihan\OneDrive\CO326\github\CO326-Computer-Interfacing\Project-USB\USB-PIC-IO\algo\USB-PIC-IO-Algo.fcfx
//**  Title:         
//**  Description:   
//**  Device:        PIC.18F.18F4550
//**  
//**  Generated by:  Flowcode v7.1.1.0
//**  Date:          Sunday, January 13, 2019 14:22:21
//**  Users:         1
//**  Registered to: 
//**  Licence key:   BYTE1
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixtsl.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_CAL_PIC

#define MX_CLK_SPEED 4000000

#define FCP_NULL Unconnected_Port



#include <xc.h>
#include <math.h>

__PROG_CONFIG(0x1, 0xFCFF);
__PROG_CONFIG(0x2, 0xFEFF);
__PROG_CONFIG(0x3, 0xFFFF);
__PROG_CONFIG(0x4, 0xFF9B);
__PROG_CONFIG(0x5, 0xFFFF);
__PROG_CONFIG(0x6, 0xFFFF);
__PROG_CONFIG(0x7, 0xFFFF);

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "E:\Program Files (x86)\Flowcode 7\CAL\internals.c"



/*========================================================================*\
   Use :panel
       :Variable declarations
       :Macro function declarations
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_UINT8 FCV_INBYTE1 = (0x0);
MX_GLOBAL MX_UINT8 FCV_INBYTE0 = (0x0);
MX_GLOBAL MX_UINT8 FCV_OUTBYTE1 = (0x0);
MX_GLOBAL MX_UINT8 FCV_OUTBYTE0;


/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "E:\Program Files (x86)\Flowcode 7\CAL\includes.c"


/*========================================================================*\
   Use :panel
       :Macro implementations
\*========================================================================*/


/*========================================================================*\
   Use :Main
\*========================================================================*/
void main()
{
ADCON0=0x00;
ADCON1 = 0x0F;
UCFG = 0x08;
cr_bit(PIE2, USBIE);




	// Loop
	// Loop: While 1
	while (1)
	{

		// Output
		// Output: 0b00000110 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (6));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Input
		// Input: PORTD -> inByte0
		FCV_INBYTE0 = FCP_GET(F, D, 0xFF, 0);
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b00001001 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (9));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Input
		// Input: PORTD -> inByte1
		FCV_INBYTE1 = FCP_GET(F, D, 0xFF, 0);
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b00000101 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (5));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Calculation
		// Calculation:
		//  outByte0 = inByte0
		//  outByte1 = inByte0 XOR inByte1
		FCV_OUTBYTE0 = FCV_INBYTE0;
		FCV_OUTBYTE1 = FCV_INBYTE0 ^ FCV_INBYTE1;

		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: outByte0 -> PORTD
		FCP_SET(F, D, 0xFF, 0, (FCV_OUTBYTE0));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b00010101 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (21));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b00000101 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (5));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: outByte1 -> PORTD
		FCP_SET(F, D, 0xFF, 0, (FCV_OUTBYTE1));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b01000101 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (69));
		// Delay
		// Delay: 1 ms
		FCI_DELAYBYTE_MS(1);

		// Output
		// Output: 0b00000101 -> PORTB
		FCP_SET(F, B, 0xFF, 0, (5));
		// Delay
		// Delay: 10 ms
		FCI_DELAYBYTE_MS(10);


	}

	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
void MX_INTERRUPT_MACRO(void)
{

}




